name: 01-Building Blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!!"

  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust the Node.js version according to your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build
